thread 'main' panicked at src/main.rs:404:10:
called `Result::unwrap()` on an `Err` value: Unknown("Failed to start a forkserver", ErrorBacktrace)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
